# Halaja Seed Bank - Extensive list of questions for dynamic generation

HALAJA_BANK = [
    # SHABAT
    {
        'category': 'Shabat',
        't_es': '¿Cuál es el estado halájico de un objeto que no tiene uso permitido en Shabat (Muktze)?',
        't_en': 'What is the halakhic status of an object that has no permitted use on Shabbat (Muktze)?',
        't_he': 'מהו הסטטוס ההלכתי של חפץ שאין לו שימוש מותר בשבת (מוקצה)?',
        'a_es': 'Está prohibido moverlo salvo excepciones específicas', 'a_en': 'It is forbidden to move it except for specific exceptions', 'a_he': 'אסור בטלטול אלא במקרים חריגים',
        'b_es': 'Se puede mover solo con la mano izquierda', 'b_en': 'It can be moved only with the left hand', 'b_he': 'מותר לטלטל רק ביד שמאל',
        'c_es': 'Se puede mover si es para limpiar el lugar', 'c_en': 'It can be moved if it is to clean the place', 'c_he': 'מותר לטלטל לצורך ניקוי המקום בלבד',
    },
    {
        'category': 'Shabat',
        't_es': '¿Se permite lavar platos con una esponja común en Shabat?',
        't_en': 'Is it permitted to wash dishes with a common sponge on Shabbat?',
        't_he': 'האם מותר לשטוף כלים עם ספוג רגיל בשבת?',
        'a_es': 'No, por la prohibición de exprimir (Sjitá)', 'a_en': 'No, due to the prohibition of squeezing (Sjita)', 'a_he': 'אסור משום סחיטה',
        'b_es': 'Sí, si se usa mucha agua', 'b_en': 'Yes, if plenty of water is used', 'b_he': 'מותר אם משתמשים בהרבה מים',
        'c_es': 'Sí, si no se usa detergente', 'c_en': 'Yes, if no detergent is used', 'c_he': 'מותר ללא סבון כלים',
    },
    {
        'category': 'Shabat',
        't_es': '¿Qué es "Amira LeNojri"?',
        't_en': 'What is "Amira LeNojri"?',
        't_he': 'מהי "אמירה לנוכרי"?',
        'a_es': 'Pedir a un no judío que realice un trabajo prohibido en Shabat', 'a_en': 'Asking a non-Jew to perform work forbidden on Shabbat', 'a_he': 'בקשה מגוי שיעשה מלאכה האסורה בשבת',
        'b_es': 'Invitar a un no judío a la cena de Shabat', 'b_en': 'Inviting a non-Jew to Shabbat dinner', 'b_he': 'הזמנת גוי לסעודת שבת',
        'c_es': 'Hablar en un idioma extranjero durante el rezo', 'c_en': 'Speaking in a foreign language during prayer', 'c_he': 'דיבור בשפה זרה בזמן התפילה',
    },
    {
        'category': 'Shabat',
        't_es': '¿Cuál es la regla para calentar comida sólida y seca en Shabat?',
        't_en': 'What is the rule for heating solid, dry food on Shabbat?',
        't_he': 'מה הכלל לגבי חימום מאכל יבש בשבת?',
        'a_es': 'Se permite sobre una plata/calentador si ya está cocida (Ein Bishul Ajar Bishul)', 'a_en': 'Permitted on a blech/warmer if already cooked (Ein Bishul Achar Bishul)', 'a_he': 'מותר על הפלטה אם המאכל מבושל כל צורכו',
        'b_es': 'Está prohibido calentar cualquier cosa', 'b_en': 'It is forbidden to heat anything', 'b_he': 'אסור לחמם כל דבר',
        'c_es': 'Solo se permite cocinar desde cero', 'c_en': 'Only cooking from scratch is permitted', 'c_he': 'מותר לבשל רק מההתחלה',
    },
    # KASHRUT
    {
        'category': 'Kashrut (Carne y Leche)',
        't_es': '¿Qué es "Tevilát Kelím"?',
        't_en': 'What is "Tevilat Kelim"?',
        't_he': 'מהי "טבילת כלים"?',
        'a_es': 'Sumergir utensilios comprados a un no judío en una Mikve', 'a_en': 'Immersing utensils bought from a non-Jew in a Mikvah', 'a_he': 'טבילת כלים שנקנו מגוי במקווה טהרה',
        'b_es': 'Lavar los platos con agua bendita', 'b_en': 'Washing dishes with holy water', 'b_he': 'שטיפת הכלים במים קדושים',
        'c_es': 'Quemar los restos de comida no kosher', 'c_en': 'Burning non-kosher food remains', 'c_he': 'שריפת שאריות אוכל לא כשר',
    },
    {
        'category': 'Kashrut (Carne y Leche)',
        't_es': '¿Se permite comer pescado con carne según la Halajá?',
        't_en': 'Is it permitted to eat fish with meat according to Halacha?',
        't_he': 'האם מותר לאכול דג עם בשר לפי ההלכה?',
        'a_es': 'No, por razones de peligro (Sakaná)', 'a_en': 'No, due to danger (Sakana)', 'a_he': 'אסור משום סכנה',
        'b_es': 'Sí, es una combinación recomendada', 'b_en': 'Yes, it is a recommended combination', 'b_he': 'מותר, זה שילוב מומלץ',
        'c_es': 'Solo en festivales como Pesaj', 'c_en': 'Only on festivals like Pesach', 'c_he': 'מותר רק בחגים כמו פסח',
    },
    {
        'category': 'Kashrut (Carne y Leche)',
        't_es': '¿Cuánto tiempo debe esperarse después de comer pollo antes de ingerir lácteos?',
        't_en': 'How long must one wait after eating chicken before consuming dairy?',
        't_he': 'כמה זמן יש להמתין לאחר אכילת עוף לפני מוצרי חלב?',
        'a_es': 'Igual que con la carne vacuna (6 horas)', 'a_en': 'Same as with beef (6 hours)', 'a_he': 'כמו בבשר בקר (שש שעות)',
        'b_es': 'Solo una hora', 'b_en': 'Only one hour', 'b_he': 'שעה אחת בלבד',
        'c_es': 'No es necesario esperar', 'c_en': 'Waiting is not necessary', 'c_he': 'אין צורך להמתין כלל',
    },
    # TEFILA
    {
        'category': 'Tefilá',
        't_es': '¿Cuál es el tiempo límite (Zmán) para la Tefilát Shajarit (mañana)?',
        't_en': 'What is the time limit (Zman) for Tefilat Shacharit (morning)?',
        't_he': 'מהו הזמן האחרון לתפילת שחרית?',
        'a_es': 'Cuatro horas proporcionales después del amanecer', 'a_en': 'Four proportional hours after sunrise', 'a_he': 'סוף ארבע שעות זמניות',
        'b_es': 'Hasta las 12 del mediodía exactamente', 'b_en': 'Until exactly 12 noon', 'b_he': 'עד השעה 12 בצהריים בדיוק',
        'c_es': 'Durante todo el día', 'c_en': 'Throughout the entire day', 'c_he': 'במשך כל היום',
    },
    {
        'category': 'Tefilá',
        't_es': '¿Qué debe hacer quien olvidó decir "Mashiv HaRúaj" en la Amidá de invierno?',
        't_en': 'What should one do who forgot to say "Mashiv HaRuach" in the winter Amidah?',
        't_he': 'מי ששכח לומר "משיב הרוח ומוריד הגשם", מה דינו?',
        'a_es': 'Si ya terminó la bendición, debe volver a empezar la Amidá', 'a_en': 'If you already finished the blessing, you must restart the Amidah', 'a_he': 'אם סיים את הברכה, חוזר לראש התפילה',
        'b_es': 'Puede decirlo al final en Elokai Netzor', 'b_en': 'Can say it at the end in Elokai Netzor', 'b_he': 'יכול לומר זאת בסוף ב"אלוקי נצור"',
        'c_es': 'No importa, puede seguir', 'c_en': 'It doesn\'t matter, can continue', 'c_he': 'זה לא משנה, יכול להמשיך',
    },
    # FESTIVIDADES
    {
        'category': 'Festividades',
        't_es': '¿Qué es "Eruv Tavshilin"?',
        't_en': 'What is "Eruv Tavshilin"?',
        't_he': 'מהו "עירוב תבשילין"?',
        'a_es': 'Permiso para cocinar en un día festivo que cae viernes para el Shabat', 'a_en': 'Permission to cook on a holiday that falls on Friday for Shabbat', 'a_he': 'היתר להכין לצורך שבת ביו"ט שחל בערב שבת',
        'b_es': 'Una forma de cargar objetos en la calle en Shabat', 'b_en': 'A way to carry objects in the street on Shabbat', 'b_he': 'דרך לטלטל חפצים ברשות הרבים בשבת',
        'c_es': 'La mezcla de harinas para la Matzá', 'c_en': 'The mixture of flours for Matzah', 'c_he': 'ערבוב קמחים לצורך אפיית מצות',
    },
    {
        'category': 'Festividades',
        't_es': '¿Cuántas velas se encienden en total la octava noche de Janucá (sin contar el Shamash)?',
        't_en': 'How many candles are lit in total on the eighth night of Hanukkah (not counting the Shamash)?',
        't_he': 'כמה נרות מדליקים ביום השמיני של חנוכה (ללא השמש)?',
        'a_es': 'Ocho velas', 'a_en': 'Eight candles', 'a_he': 'שמונה נרות',
        'b_es': 'Nueve velas', 'b_en': 'Nine candles', 'b_he': 'תשעה נרות',
        'c_es': 'Cuarenta y cuatro velas', 'c_en': 'Forty-four candles', 'c_he': 'ארבעים וארבעה נרות',
    },
    # GENERALES
    {
        'category': 'Leyes Generales',
        't_es': '¿Qué es "Lashón Hará" según la ley judía?',
        't_en': 'What is "Lashon Hara" according to Jewish law?',
        't_he': 'מהו "לשון הרע" לפי ההלכה?',
        'a_es': 'Hablar mal de otra persona, incluso si la información es verdadera', 'a_en': 'Speaking poorly of another person, even if the information is true', 'a_he': 'דיבור רע על הזולת, אפילו אם הדברים אמת',
        'b_es': 'Mentir sobre alguien para beneficiarse', 'b_en': 'Lying about someone for personal gain', 'b_he': 'שקר המופץ על אדם לצורך רווח אישי',
        'c_es': 'Hablar un idioma que otros no entienden', 'c_en': 'Speaking a language others do not understand', 'c_he': 'דיבור בשפה שאחרים אינם מבינים אותה',
    },
]
