# Halaja Seed Bank - Extensive list of questions for dynamic generation

HALAJA_BANK = [
    # SHABAT (Hiljot Shabat - Mishna Berura)
    {
        'category': 'Shabat',
        't_es': 'De acuerdo al Biur Halajá, ¿cuál es el estado de "Davar SheEino Mitkaven" en una Melajá de la Torá?',
        't_en': 'According to the Biur Halacha, what is the status of "Davar SheEino Mitkaven" in a Torah-level Melacha?',
        't_he': 'לפי הביאור הלכה, מהו הדין ב"דבר שאינו מתכוון" במלאכה דאורייתא?',
        'a_es': 'Está permitido (Mutar) siempre que no sea un "Psik Reishei"', 'a_en': 'It is permitted (Mutar) as long as it is not a "Psik Reishei"', 'a_he': 'מותר, כל עוד אינו "פסיק רישא"',
        'b_es': 'Está prohibido por decreto rabínico (Asur MiDrabanan)', 'b_en': 'It is forbidden by rabbinic decree (Asur MiDrabanan)', 'b_he': 'אסור מדרבנן בכל מקרה',
        'c_es': 'Se considera una transgresión de la Torá (Dauraita)', 'c_en': 'It is considered a Torah transgression (Dauraita)', 'c_he': 'נחשב למלאכה דאורייתא',
    },
    {
        'category': 'Shabat',
        't_es': 'En la Melajá de "Boshél" (cocinar), ¿qué se considera "Kalé HaBishul" (fácil de cocinar) según el Mishna Berura?',
        't_en': 'In the Melacha of "Boshel" (cooking), what is considered "Kalei HaBishul" (easy to cook) according to the Mishna Berura?',
        't_he': 'במלאכת "מבשל", מה נחשב ל"קלי הבישול" לפי המשנה ברורה?',
        'a_es': 'Cosas como el té o el arenque, que se cocinan incluso en Kli Shení', 'a_en': 'Items like tea or herring, which cook even in a Kli Sheni', 'a_he': 'דברים כגון תה או דג מלוח, המתבשלים אף בכלי שני',
        'b_es': 'Cualquier líquido que ya fue hervido previamente', 'b_en': 'Any liquid that was previously boiled', 'b_he': 'כל נוזל שהורתח כבר בעבר',
        'c_es': 'Solo alimentos sólidos que no han sido procesados', 'c_en': 'Only solid foods that have not been processed', 'c_he': 'רק מאכלים מוצקים שלא עברו עיבוד',
    },
    {
        'category': 'Shabat',
        't_es': '¿Cuál es la definición de "Ojel mitoj Psolet" en Borer para que sea permitido?',
        't_en': 'What is the definition of "Ochel mi-toch Psolet" in Borer to be permitted?',
        't_he': 'מהי ההגדרה של "אוכל מתוך פסולת" במלאכת בורר כדי שיהיה מותר?',
        'a_es': 'Tomar lo que se desea, con la mano, para uso inmediato (LeAltar)', 'a_en': 'Taking what is desired, by hand, for immediate use (LeAltar)', 'a_he': 'לקיחת החפץ שרוצים, ביד, לשימוש מיידי (לאלתר)',
        'b_es': 'Usar un colador para separar el líquido del sólido', 'b_en': 'Using a strainer to separate the liquid from the solid', 'b_he': 'שימוש במסננת להפרדת הנוזל מהמוצק',
        'c_es': 'Quitar la cáscara de una fruta para comerla después de la comida', 'c_en': 'Removing the peel of a fruit to eat it after the meal', 'c_he': 'הסרת הקליפה כדי לאכול את הפרי לאחר הסעודה',
    },
    {
        'category': 'Shabat',
        't_es': 'Respecto a "Muktze", ¿qué es el "Bassis LeDavar HaAsur"?',
        't_en': 'Regarding "Muktze", what is "Bassis LeDavar HaAsur"?',
        't_he': 'בהלכות מוקצה, מהו "בסיס לדבר האסור"?',
        'a_es': 'Un objeto permitido que sostiene algo prohibido colocado intencionalmente antes de Shabat', 'a_en': 'A permitted object holding a forbidden item intentionally placed before Shabbat', 'a_he': 'כלי היתר שהונח עליו דבר איסור בכוונה מערב שבת',
        'b_es': 'Cualquier mesa que tenga una vela encima durante Shabat', 'b_en': 'Any table that has a candle on it during Shabbat', 'b_he': 'כל שולחן שיש עליו נר דולק במהלך השבת',
        'c_es': 'Un objeto roto que ya no tiene utilidad funcional', 'c_en': 'A broken object that no longer has functional utility', 'c_he': 'חפץ שנשבר ואין לו עוד שימוש פונקציונלי',
    },
    # TEFILA (Hiljot Tefila - Mishna Berura)
    {
        'category': 'Tefilá',
        't_es': 'Si alguien tiene duda si leyó el Shemá Israel, ¿qué dictamina el Mishna Berura siguiendo la regla de "Safek Dauraita"?',
        't_en': 'If someone is in doubt whether they read the Shema Israel, what does the Mishna Berura rule following the "Safek Dauraita" principle?',
        't_he': 'מי שנתפלל וספק לו אם קרא קריאת שמע, מה הדין לפי המשנה ברורה?',
        'a_es': 'Debe volver a leerlo por ser un precepto de la Torá', 'a_en': 'Must read it again because it is a Torah commandment', 'a_he': 'צריך לחזור ולקרוא כי ספק דאורייתא לחומרא',
        'b_es': 'No debe volver a leerlo para evitar una bendición en vano', 'b_en': 'Must not read it again to avoid a blessing in vain', 'b_he': 'אינו חוזר כדי שלא יבוא לברכה לבטלה',
        'c_es': 'Basta con leer solo el primer versículo', 'c_en': 'It is enough to read only the first verse', 'c_he': 'די בקריאת הפסוק הראשון בלבד',
    },
    {
        'category': 'Tefilá',
        't_es': '¿Cuál es la halajá si se terminó la Amidá y se olvidó decir "Yaalé VeYavó" en Rosh Jodesh (Shajarit/Minjá)?',
        't_en': 'What is the Halakha if one finished the Amidah and forgot to say "Yaaleh VeYavo" on Rosh Chodesh (Shacharit/Mincha)?',
        't_he': 'מי שסיים תפילת עמידה ושכח "יעלה ויבוא" בראש חודש (שחרית/מנחה), מה דינו?',
        'a_es': 'Debe repetir la Amidá completa', 'a_en': 'Must repeat the entire Amidah', 'a_he': 'חייב לחזור לראש התפילה',
        'b_es': 'Se considera cumplida la obligación y no repite', 'b_en': 'The obligation is considered fulfilled and does not repeat', 'b_he': 'יצא ידי חובה ובדיעבד אינו חוזר',
        'c_es': 'Repite solamente la bendición de Retzé', 'c_en': 'Repeats only the blessing of Retze', 'c_he': 'חוזר רק לברכת רצה',
    },
    # KASHRUT
    {
        'category': 'Kashrut (Carne y Leche)',
        't_es': '¿Cuál es la regla de "Nat Bar Nat" (Guepet) respecto a un recipiente de carne limpio usado para comida láctea?',
        't_en': 'What is the rule of "Nat Bar Nat" (Gepet) regarding a clean meat vessel used for dairy food?',
        't_he': 'מהו הדין ב"נ"ט בר נ"ט" לגבי כלי בשרי נקי ששימש למאכל פרווה שנאכל עם חלב?',
        'a_es': 'Está permitido si el recipiente estaba limpio y no se usó en 24h', 'a_en': 'It is permitted if the vessel was clean and not used in 24h', 'a_he': 'מותר לכתחילה אם הכלי אינו בן יומו',
        'b_es': 'Está prohibido bajo cualquier circunstancia', 'b_en': 'It is forbidden under any circumstances', 'b_he': 'אסור בכל מקרה לאכול יחד',
        'c_es': 'Depende si el alimento es picante (Davár Jaríf)', 'c_en': 'Dependencies on whether the food is spicy (Davar Charif)', 'c_he': 'תלוי אם המאכל הוא "דבר חריף"',
    },
    # FESTIVIDADES
    {
        'category': 'Festividades',
        't_es': '¿Cuál es la medida mínima (Shiur) de una Sucá según la Halajá?',
        't_en': 'What is the minimum measure (Shiur) of a Sukkah according to Halakha?',
        't_he': 'מהו השיעור המינימלי של סוכה כשרה?',
        'a_es': '7 por 7 Tefajim', 'a_en': '7 by 7 Tefachim', 'a_he': 'שבעה על שבעה טפחים',
        'b_es': '10 por 10 Tefajim', 'b_en': '10 by 10 Tefachim', 'b_he': 'עשרה על עשרה טפחים',
        'c_es': '4 por 4 Amót', 'c_en': '4 by 4 Amot', 'c_he': 'ארבע על ארבע אמות',
    },
    # GENERALES
    {
        'category': 'Leyes Generales',
        't_es': '¿Qué define a un "Davár Jaríf" (objeto picante) y cómo afecta la absorción de sabores?',
        't_en': 'What defines a "Davar Charif" (spicy object) and how does it affect the absorption of flavors?',
        't_he': 'מה נחשב ל"דבר חריף" וכיצד הוא משפיע על בליעת הטעמים בכלים?',
        'a_es': 'Cosas como cebolla o limón, que pueden "despertar" el sabor incluso de un plato no usado en 24h', 'a_en': 'Items like onion or lemon, which can "awaken" flavor even from a dish not used in 24h', 'a_he': 'דברים כגון בצל או לימון, המעוררים טעם פגום לשבח',
        'b_es': 'Solo alimentos que queman la lengua por su temperatura', 'b_en': 'Only foods that burn the tongue due to their temperature', 'b_he': 'רק מאכלים חמים מאוד שכויה בם היד',
        'c_es': 'Cualquier alimento que contenga sal en grandes cantidades', 'c_en': 'Any food containing salt in large quantities', 'c_he': 'כל מאכל מלוח מאוד כציר',
    },
    {
        'category': 'Leyes Generales',
        't_es': '¿Cuál es la regla de "Ikar VeTafel" (Principal y Secundario) en las bendiciones de comida?',
        't_en': 'What is the rule of "Ikar VeTafel" (Primary and Secondary) in food blessings?',
        't_he': 'מהו הכלל ב"עיקר וטפל" בברכות הנהנין?',
        'a_es': 'Se bendice solo por el principal y esto exime al secundario', 'a_en': 'One blesses only for the primary and this exempts the secondary', 'a_he': 'מברך על העיקר ופוטר את הטפל',
        'b_es': 'Se deben decir ambas bendiciones por separado', 'b_en': 'Both blessings must be said separately', 'b_he': 'צריך לברך על שניהם בנפרד',
        'c_es': 'Depende de cuál de los dos sea el más grande en tamaño', 'c_en': 'Depends on which of the two is larger in size', 'c_he': 'תלוי מי מהם גדול יותר בכמותו',
    },
    {
        'category': 'Shabat',
        't_es': '¿Cuándo se permite mover un objeto "Kli SheMeLajtó LeIssur" (herramienta de trabajo prohibido) en Shabat?',
        't_en': 'When is it permitted to move a "Kli SheMelachto LeIssur" (tool for forbidden work) on Shabbat?',
        't_he': 'מתי מותר לטלטל "כלי שמלאכתו לאיסור" בשבת?',
        'a_es': 'Solo para usar el objeto mismo (LeGufó) o su lugar (LeMekomó)', 'a_en': 'Only to use the object itself (LeGufo) or its place (LeMekomo)', 'a_he': 'לצורך גופו או לצורך מקומו בלבד',
        'b_es': 'En cualquier momento si es para evitar que se rompa', 'b_en': 'At any time if it is to prevent it from breaking', 'b_he': 'בכל זמן כדי שלא יישבר',
        'c_es': 'Está prohibido moverlo bajo cualquier circunstancia', 'c_en': 'It is forbidden to move it under any circumstances', 'c_he': 'אסור לטלטלו בכל מקרה',
    },
    {
        'category': 'Kashrut (Carne y Leche)',
        't_es': '¿Qué es un "Kli Shení" y cómo afecta la halajá de cocinar (Bishul)?',
        't_en': 'What is a "Kli Sheni" and how does it affect the Halakha of cooking (Bishul)?',
        't_he': 'מהו "כלי שני" וכיצד הוא משפיע על הלכות בישול?',
        'a_es': 'El recipiente al que se trasvasó el contenido del fuego; generalmente no cocina (salvo Kalé HaBishul)', 'a_en': 'The vessel to which the contents of the fire were transferred; generally does not cook (except Kalei HaBishul)', 'a_he': 'הכלי שאליו הועבר התוכן מהכלי שעמד על האש; אינו מבשל (פרט לקלי הבישול)',
        'b_es': 'El recipiente que está directamente sobre el fuego', 'b_en': 'The vessel that is directly on the fire', 'b_he': 'הכלי שעומד ישירות על האש',
        'c_es': 'Un plato que ha estado frío por más de 24 horas', 'c_en': 'A dish that has been cold for more than 24 hours', 'c_he': 'כלי שהיה צונן מעל 24 שעות',
    },
]
